"""Seed LLM (Chat API) — the Script Agent + a Seedance prompt optimizer.

The system prompts encode the Seedream/Seedance advertising prompt rules
distilled in PROMPTING.md (which is also the knowledge of the `sd25-pe` skill).
"""

import json

import requests

from . import config as C
from schemas import AD_PLAN_SCHEMA

# Shared house rules — the ad prompt framework + Seedance 2.5 structure.
PROMPT_RULES = """\
You follow the BytePlus advertising prompt playbook and the Seedance 2.5 prompt guide:

AD FRAMEWORK (required): Subject (person/product) + Selling-point demonstration
(turn each claim into a concrete micro-action or pain-point scene) + commercial
intent. Optional: consumption scenario & tone, camera language (the visual hook),
audio (SFX/beat), post-production constraints.
NATIVE STRUCTURE: Hook + Product + CTA. First ~3s = a strong visual/auditory hook;
middle = clear product demo; end = explicit CTA. Cut every 2-3 seconds.

SEEDANCE 2.5 director_brief STRUCTURE (write it exactly like this):
1) One-sentence summary: Subject + Location + Event + Style + Camera.
2) Asset bindings (Seedream/Seedance convention): cite references INLINE in natural
   language as @image1, @image2, @audio1 … each with an explicit match instruction, e.g.
   "the presenter from @image1; face and build match @image1 exactly", "the exact product
   from @image2, its design/colour/materials unchanged", "@audio1 = the voiceover, lip-sync
   to it". Order when present: @image1 = presenter, then product/logo/style, then @audio1.
3) Detailed plot on a continuous integer-second timeline with NO gaps
   (e.g. 0-3s ... 3-6s ...), ~2-3s per beat. Each beat: visuals, camera movement,
   action, dialogue in double quotes, sound. Tag lines with roles like [Subject],
   [Selling Point Demonstration], [Consumption Scenario and Tone],
   [Visual Hook and Camera Movement], [Audio-Visual Synchronization],
   [Post-Production Constraints].
4) Keep every spoken line in double quotes. Put Hindi VO in quotes with the natural
   Devanagari text.
5) Negatives only for subtitles/audio.

COMPLIANCE: no absolute efficacy/medical claims; promo/discount claims must be real
and match the landing page; respect cultural/religious norms; clear IP/likeness;
don't exaggerate demos.
"""

SYSTEM = (
    "You are an expert short-form advertising creative director and scriptwriter for "
    "vertical (9:16) social video ads generated by Seedance 2.5 as ONE continuous "
    "piece of video (the model handles cuts/pacing). You write bilingual Hindi + "
    "English ad copy: natural Hindi (Devanagari) voiceover with English product terms. "
    + PROMPT_RULES
)


def _text_rule(model_text):
    if model_text:
        return ("ON-SCREEN TEXT (HYBRID): the video may render ONLY very short English/"
                "number badges (e.g. '₹2.45 Lakh', '7-Yr Warranty') — put those in each "
                "scene's on_screen_text and mention them in director_brief. ALL Hindi text, "
                "phone numbers, addresses and the logo go in overlay_text (post), never in "
                "on_screen_text.")
    return ("ON-SCREEN TEXT (POST-ONLY): the video renders NO text — leave on_screen_text "
            "empty for every scene, put all text in overlay_text, and include \"no subtitles\" "
            "in director_brief.")


def generate_ad_plan(brief, duration=20, aspect="9:16", language="Hindi + English",
                     model_text=False, model_id=None):
    """Seed LLM with strict json_schema → (ad_plan_dict, http_status)."""
    if not C.api_key():
        return {"error": "ARK_API_KEY not configured"}, 500
    mid = (model_id or C.llm_model()).strip()
    if not mid:
        return {"error": "SEED_LLM_MODEL_ID not configured (paste a brief/plan instead, or set it in .env)"}, 500

    user = (
        f"Create an ad plan.\n\nBRIEF:\n{brief}\n\n"
        f"Constraints: language = {language}; total duration = {duration} seconds "
        f"(all scene times fit within 0..{duration}, continuous, no gaps); aspect = {aspect}.\n"
        f"{_text_rule(model_text)}\n"
        "Write 3-6 scenes on a single timeline following Hook + Product + CTA, and a "
        "director_brief in the Seedance 2.5 structure above (one-sentence summary, asset "
        "bindings citing @image1/@audio1 inline with match instructions, tagged timestamped "
        "beats with dialogue in double quotes).\n"
        "Also fill the top-level 'presenter' field with a concise physical description of the "
        "on-screen presenter (age, gender, look, wardrobe), and the top-level 'wardrobe' field with "
        "the presenter's exact outfit (garments + colours) that stays IDENTICAL in every scene unless a "
        "scene deliberately changes it. Keep the presenter in this same outfit throughout director_brief "
        "and every beat; do not vary the clothing between beats.\n"
        "IMPORTANT — keyframe_prompt for each scene: this is a CLEAN photographic STILL for the "
        "Seedream storyboard, NOT the video. Refer to the person ONLY as 'the presenter' and to the "
        "product ONLY generically (e.g. 'the product', 'the shoe', 'the car') — do NOT describe the "
        "presenter's face/hair/age/ethnicity/build/wardrobe, and do NOT invent the product's brand, "
        "colour, model or markings (identity AND product appearance come from the reference images the "
        "app binds as @image1, @image2). Describe ONLY: the presenter's pose/action, how the product is "
        "shown, the environment, camera framing and lighting, in Seedream's 6-part style. Do NOT include "
        "camera cuts, transitions, motion, floating icons, holograms, shields, calculators, graphic "
        "props, UI elements, badges, on-screen text or Hindi text. Show exactly ONE product/vehicle."
    )
    return _chat_schema(mid, SYSTEM, user)


def optimize_seedance_prompt(prompt, duration=20, aspect="9:16", model_id=None):
    """The sd25-pe equivalent: rewrite a rough prompt into the Seedance 2.5 structure.
    Returns ({optimized: str}, http_status)."""
    if not C.api_key():
        return {"error": "ARK_API_KEY not configured"}, 500
    mid = (model_id or C.llm_model()).strip()
    if not mid:
        return {"error": "SEED_LLM_MODEL_ID not configured"}, 500
    sys = ("You are a Seedance 2.5 prompt optimizer (equivalent to the sd25-pe skill). "
           "Rewrite the user's rough prompt into a single high-quality Seedance 2.5 prompt. "
           + PROMPT_RULES +
           " Output ONLY the rewritten prompt text, no preamble.")
    user = (f"Rewrite this into an optimized Seedance 2.5 prompt for a {duration}s, {aspect} ad. "
            f"Keep any @image/@audio bindings and spoken lines.\n\nPROMPT:\n{prompt}")
    payload = {"model": mid, "messages": [{"role": "system", "content": sys},
                                          {"role": "user", "content": user}],
               "thinking": {"type": "disabled"}}
    try:
        resp = requests.post(C.LLM_ENDPOINT, headers=C.bearer_headers(), json=payload, timeout=120)
        data = C.safe_json(resp)
        if resp.status_code not in (200, 201):
            return {"error": data, "http_status": resp.status_code}, resp.status_code
        content = (((data.get("choices") or [{}])[0]).get("message") or {}).get("content", "")
        return {"optimized": content.strip(), "raw": data}, 200
    except Exception as e:
        return {"error": str(e)}, 500


def _chat_schema(mid, system, user):
    payload = {
        "model": mid,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
        "response_format": {"type": "json_schema",
                            "json_schema": {"name": "ad_plan", "strict": True, "schema": AD_PLAN_SCHEMA}},
        "thinking": {"type": "disabled"},
    }
    try:
        resp = requests.post(C.LLM_ENDPOINT, headers=C.bearer_headers(), json=payload, timeout=120)
        data = C.safe_json(resp)
        if resp.status_code not in (200, 201):
            return {"error": data, "http_status": resp.status_code}, resp.status_code
        content = (((data.get("choices") or [{}])[0]).get("message") or {}).get("content", "")
        try:
            plan = json.loads(content)
        except Exception:
            return {"error": "Model did not return valid JSON", "raw": content[:800]}, 502
        return {"plan": plan, "raw": data}, 200
    except Exception as e:
        return {"error": str(e)}, 500
